name: Deploy frontend application
'on':
    push:
        branches:
        - prod

      
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Set up docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME}}
                    password: ${{ secrets.DOCKER_HUB_TOKEN}}
            -
                name: prepare the docker-compose-prod run
                run: |
                    ls -l
            -
                name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/234-deploylab-frontend:latest
            -
                name: copy file via ssh password
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.HOST_SERVER }}
                    username: ${{ secrets.HOST_USER_NAME }}
                    key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
                    port: 22
                    source: "docker-compose-prod.yml"
                    target: "/home/ubuntu/frontendProd"
            -
                name: docker compose
                uses: appleboy/ssh-action@v1.2.1
                with:
                    host: ${{ secrets.HOST_SERVER }}
                    username: ${{ secrets.HOST_USER_NAME}}
                    key: ${{ secrets.HOST_SSH_PRIVATE_KEY}}
                    port: 22
                    script: |
                        cd /home/ubuntu/frontendProd
                        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
                        docker compose down
                        docker compose pull
                        docker compose -f docker-compose-prod.yml up -d
                        rm -rf /home/ubuntu/frontendProd